### ISSUE TITLE
[BUG] ImportError: cannot import name 'PeftConfig' from 'peft.utils' 

### ISSUE THREAD

**Issue by RickMeow** [OpenLMLab/collie#109]
**Describe**
In the initial configuration, I encountered the problem `"ImportError: cannot import name 'PeftConfig' from 'peft.utils'",` while I was still in the testing phase, and used the sample code without making any modifications.
(There are almost no instructions on the web about this bug, which amazes me.)

**To Reproduce**

1. `conda create -n collie python=3.10` or `conda create -n collie python=3.8`
2. `pip install collie-lm -i https://pypi.tuna.tsinghua.edu.cn/simple/`
3. `cd collie/examples`
4. run any py code file: `python finetune_moss_for_training.py`
(I tried to change the address of the model to a local address and make the appropriate changes, but I get the error without modifying the code, which should be an environment configuration issue.)

**System info**
- OS: Ubuntu 20.04.6 LTS
- Configured as 3 groups with 8*A100 graphics cards (total of 24 A100-40G graphics cards)
- Python = 3.10
- Others:
```
Package                  Version
------------------------ ----------
absl-py                  1.4.0
accelerate               0.22.0
anyio                    3.7.1
appdirs                  1.4.4
beautifulsoup4           4.12.2
bitsandbytes             0.41.1
cachetools               5.3.1
certifi                  2023.7.22
charset-normalizer       3.2.0
click                    8.1.7
cmake                    3.27.2
collie-lm                1.0.3
deepspeed                0.10.2
docker-pycreds           0.4.0
einops                   0.6.1
exceptiongroup           1.1.3
fastapi                  0.103.1
filelock                 3.12.3
fsspec                   2023.9.0
gitdb                    4.0.10
GitPython                3.1.34
google                   3.0.0
google-auth              2.22.0
google-auth-oauthlib     1.0.0
grpcio                   1.57.0
hjson                    3.1.0
huggingface-hub          0.16.4
idna                     3.4
Jinja2                   3.1.2
lit                      16.0.6
Markdown                 3.4.4
markdown-it-py           3.0.0
MarkupSafe               2.1.3
mdurl                    0.1.2
megatron-core            0.2.0
mpmath                   1.3.0
networkx                 3.1
ninja                    1.11.1
numpy                    1.25.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
packaging                23.1
pandas                   2.1.0
pathtools                0.1.2
peft                     0.5.0
pip                      23.2.1
protobuf                 3.20.1
psutil                   5.9.5
py-cpuinfo               9.0.0
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pydantic                 1.10.12
Pygments                 2.16.1
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0.1
regex                    2023.8.8
requests                 2.31.0
requests-oauthlib        1.3.1
rich                     13.5.2
rsa                      4.9
safetensors              0.3.3
scipy                    1.11.2
sentencepiece            0.1.99
sentry-sdk               1.30.0
setproctitle             1.3.2
setuptools               68.0.0
six                      1.16.0
smmap                    5.0.0
sniffio                  1.3.0
soupsieve                2.5
starlette                0.27.0
sympy                    1.12
tensorboard              2.14.0
tensorboard-data-server  0.7.1
tokenizers               0.13.3
torch                    2.0.1
tqdm                     4.66.1
transformers             4.32.1
triton                   2.0.0
typing_extensions        4.7.1
tzdata                   2023.3
urllib3                  1.26.16
wandb                    0.15.9
websockets               11.0.3
Werkzeug                 2.3.7
wheel                    0.38.4
```

**Bug Report**
```
[2023-09-04 13:51:44,714] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/mnt/git/collie/examples/finetune_moss_for_training.py", line 8, in <module>
    from collie.config import CollieConfig
  File "/mnt/anaconda/envs/collie/lib/python3.10/site-packages/collie/__init__.py", line 3, in <module>
    from .config import CollieConfig
  File "/mnt/anaconda/envs/collie/lib/python3.10/site-packages/collie/config.py", line 6, in <module>
    from peft.utils import PeftConfig, PeftType
ImportError: cannot import name 'PeftConfig' from 'peft.utils' (/mnt/anaconda/envs/collie/lib/python3.10/site-packages/peft/utils/__init__.py)
```

**Comment by KaiLv69** [comment]
Hi, the newer version of the PEFT library has slightly changed the location of import, and we have also submitted a new commit (https://github.com/OpenLMLab/collie/commit/ed4f72cbc86b50b2e2b2556732dbc16fa241a5dc) based on this. 
https://github.com/OpenLMLab/collie/blob/dev/collie/config.py#L9

Please try the version in `dev` branch.

**Comment by RickMeow** [comment]
The problem is indeed solved, thanks!
